export const SET_SHOW_ALL_PROJECTS = 'SET_SHOW_ALL_PROJECTS';
export const SET_SHOW_PROJECT = 'SET_SHOW_PROJECT';
export const SET_CURR_SECTION = 'SET_CURR_SECTION';
export const SET_SCROLL_POSITION = 'SET_SCROLL_POSITION';
export const SET_PAGES_TRANSITION = 'SET_PAGES_TRANSITION';

export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED';
export const GET_PROJECTS_MAIN_IMG = 'GET_PROJECTS_MAIN_IMG';